apiVersion: v1
kind: Pod
metadata:
  name: basicwebkubepodlatest
  namespace: nsnew
spec:
  containers:
  - name: basicwebkubepodlatest
  image: 'nandha572/user-service:1.0.0-11'
  ports:
containerPort: 8098  # Port exposed by the Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: basicwebkubeservicelatest
  namespace: nsnew
spec:
  selector:
    run: basicwebkubepodlatest
  ports:

  protocol: TCP
  port: 80  # External port
  targetPort: 8098  # Port exposed by the Pod container
type: NodePort  # Service type